In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split

In [3]:
import numpy as np

In [24]:
x = np.arange(1,11).reshape(5,2)

In [25]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
y = [1,2,3,4,5]

In [29]:
x_train, y_train, x_test, y_test = train_test_split(x,y,test_size=.3)

In [30]:
x_train

array([[ 3,  4],
       [ 5,  6],
       [ 9, 10]])

In [34]:
y_train

array([[7, 8],
       [1, 2]])

In [36]:
x_test

[2, 3, 5]

In [37]:
y_test

[4, 1]

In [39]:
model = LinearRegression(normalize=True)

In [40]:
print model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)


In [42]:
model.fit(x_train,x_test)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [45]:
print model.predict(y_train)

[4. 1.]


In [46]:
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)


In [49]:
model.score()

TypeError: score() takes at least 3 arguments (1 given)